#ifndef IR_LIBRARY_IR_SYSTEM_H_
#define IR_LIBRARY_IR_SYSTEM_H_

#include "..\PMSM_FOC\ControlModules\pmsm_foc_functions.h"

#if(IR_Remote_Control == ENABLED)

#define MESSAGE_SIZE (8)
#define MAX_MESSAGES_IMC (8)

//typedef enum SPEEDLEVEL_T_t {
//	REMOTE_BUTTON_INVOCATION_SPEED_1 =100,
//	REMOTE_BUTTON_INVOCATION_SPEED_2 =200,
//	REMOTE_BUTTON_INVOCATION_SPEED_3 =250,
//	REMOTE_BUTTON_INVOCATION_SPEED_4 =300,
//	REMOTE_BUTTON_INVOCATION_SPEED_5= 340,
//} SPEEDLEVEL_T_t;

typedef enum STANDARD_MESSAGE_COMPONENT_t {
  NODE_ADDRESS = 0,
  COMMAND,
  DATA_WORD_0_HIGH,
  DATA_WORD_0_LOW,
  DATA_WORD_1_HIGH,
  DATA_WORD_1_LOW,
  CHECKSUM_HIGH,
  CHECKSUM_LOW,
} STANDARD_MESSAGE_COMPONENT_t;

#endif /*#if(IR_Remote_Control == ENABLED)*/

#endif /* IR_LIBRARY_IR_SYSTEM_H_ */
